In [1]:
import numpy as np

In [6]:
a = np.random.random(11)

In [13]:
# 1. sorting data
a = np.sort(a)
a

array([0.08582236, 0.36093487, 0.39694902, 0.41648308, 0.62676749,
       0.69586104, 0.76696553, 0.80468019, 0.90186436, 0.94429092,
       0.98482658])

4-quantile

In [14]:
# 2. get median
med = np.median(a)
med

0.695861036193352

In [20]:
# 3. divide two group by median
low_a = a[a < med]
high_a = a[a > med]
display(low_a)
display(high_a)

array([0.08582236, 0.36093487, 0.39694902, 0.41648308, 0.62676749])

array([0.76696553, 0.80468019, 0.90186436, 0.94429092, 0.98482658])

In [22]:
# 4. get median in lowers
low_med = np.median(low_a)
high_med = np.median(high_a)
display(low_med)
display(high_med)

0.3969490243976489

0.9018643621273731

In [25]:
# 5. four-quantile range
quantile_range = high_med - low_med
quantile_range

0.5049153377297242

In [26]:
# results
print(f'first four-quantile  : {low_med}')
print(f'second four-qualtile : {med}')
print(f'third four-quantile  : {high_med}')

print(f'four-quantile range  : {quantile_range}')

first four-quantile  : 0.3969490243976489
second four-qualtile : 0.695861036193352
third four-quantile  : 0.9018643621273731
four-quantile range  : 0.5049153377297242
